// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5l4Q2-tERX5zdzwoD8eTwkSqYnGc8e20',
    appId: '1:1037079397076:web:11725459b7bea44da53141',
    messagingSenderId: '1037079397076',
    projectId: 'instagram-clone-34dbe',
    authDomain: 'instagram-clone-34dbe.firebaseapp.com',
    storageBucket: 'instagram-clone-34dbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDptzHEW04QwyN7BJqaUSqUSMyy6Pls74',
    appId: '1:1037079397076:android:646a81b77b0bf963a53141',
    messagingSenderId: '1037079397076',
    projectId: 'instagram-clone-34dbe',
    storageBucket: 'instagram-clone-34dbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltQ1ydJ5dO6eI7GrE5zZOusFtnIKsiAk',
    appId: '1:1037079397076:ios:1f1b241db31ea6a9a53141',
    messagingSenderId: '1037079397076',
    projectId: 'instagram-clone-34dbe',
    storageBucket: 'instagram-clone-34dbe.appspot.com',
    iosClientId: '1037079397076-pfju70qdutjkkak24f4og1n3mkb46vb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
